name=ScalpelSpace Bus
version=0.1.0
author=ScalpelSpace
maintainer=ScalpelSpace <info@scalpelspace.com>
sentence=Arduino library short description here.
paragraph=Extended description here.
category=Communication
url=https://github.com/scalpelspace/scalpelspace_bus
architectures=*
includes=
