name=ScalpelSpace Bus
version=0.1.1
author=ScalpelSpace
maintainer=ScalpelSpace <info@scalpelspace.com>
sentence=Unified communication Arduino library for ScalpelSpace devices.
paragraph=Implement ScalpelSpace devices via standardized bus communication protocols including classic CAN using the MCP2518FD SPI-CAN breakout.
category=Communication
url=https://github.com/scalpelspace/scalpelspace_bus
architectures=*
includes=scalpelspace_bus.h
depends=ACAN2517
