/*******************************************************************************
 * VENDORED FILE - DO NOT EDIT.
 * Source: https://github.com/scalpelspace/momentum_driver
 * Version: 8b7910a (ref: v0.4.1)
 * Synced by CI tooling.
 *******************************************************************************
 */

/*******************************************************************************
 * @file momentum_can_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "momentum_can_dbc.h"

/** Private variables. ********************************************************/

static const can_signal_t state_signals[2] = {
    {
        .name = "system_state",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "mcu_temperature",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = -40.0f,
        .min_value = -40.0f,
        .max_value = 215.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t barometric_signals[3] = {
    {
        .name = "pressure",
        .start_bit = 0,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.00566f,
        .offset = 30000.0f,
        .min_value = 30000.0f,
        .max_value = 24339514.8897f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "temperature",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.0019074f,
        .offset = -40.0f,
        .min_value = -40.0f,
        .max_value = 85.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "barometric_state",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t gnss1_signals[2] = {
    {
        .name = "latitude",
        .start_bit = 0,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 4.1909516e-08f,
        .offset = 0.0f,
        .min_value = -90.0f,
        .max_value = 90.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "longitude",
        .start_bit = 32,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 8.3819032e-08f,
        .offset = 0.0f,
        .min_value = -180.0f,
        .max_value = 180.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t gnss2_signals[5] = {
    {
        .name = "speed",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.01f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 655.35f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "course",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.01f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 655.35f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "position_fix",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "satellite_count",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hdop",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.01f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 655.35f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t gnss3_signals[3] = {
    {
        .name = "altitude",
        .start_bit = 0,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.01f,
        .offset = -150.0f,
        .min_value = -150.0f,
        .max_value = 20000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "geoid_separation",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.01f,
        .offset = 0.0f,
        .min_value = -327.67f,
        .max_value = 327.67f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "gnss_state",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t quaternion_signals[4] = {
    {
        .name = "quaternion_x",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 3.05185e-05f,
        .offset = 0.0f,
        .min_value = -0.99998f,
        .max_value = 0.99998f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "quaternion_y",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 3.05185e-05f,
        .offset = 0.0f,
        .min_value = -0.99998f,
        .max_value = 0.99998f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "quaternion_z",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 3.05185e-05f,
        .offset = 0.0f,
        .min_value = -0.99998f,
        .max_value = 0.99998f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "quaternion_w",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 3.05185e-05f,
        .offset = 0.0f,
        .min_value = -0.99998f,
        .max_value = 0.99998f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t gyroscope_signals[3] = {
    {
        .name = "gyro_x",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0625f,
        .offset = 0.0f,
        .min_value = -2000.0f,
        .max_value = 2000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "gyro_y",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0625f,
        .offset = 0.0f,
        .min_value = -2000.0f,
        .max_value = 2000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "gyro_z",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0625f,
        .offset = 0.0f,
        .min_value = -2000.0f,
        .max_value = 2000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t magnetometer_signals[3] = {
    {
        .name = "mag_x",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0625f,
        .offset = 0.0f,
        .min_value = -2000.0f,
        .max_value = 2000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "mag_y",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0625f,
        .offset = 0.0f,
        .min_value = -2000.0f,
        .max_value = 2000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "mag_z",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0625f,
        .offset = 0.0f,
        .min_value = -2000.0f,
        .max_value = 2000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t accelerometer_signals[3] = {
    {
        .name = "accel_x",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0047889f,
        .offset = 0.0f,
        .min_value = -156.9f,
        .max_value = 156.9f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "accel_y",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0047889f,
        .offset = 0.0f,
        .min_value = -156.9f,
        .max_value = 156.9f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "accel_z",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0047889f,
        .offset = 0.0f,
        .min_value = -156.9f,
        .max_value = 156.9f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t linear_accelerometer_signals[3] = {
    {
        .name = "lin_accel_x",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0047889f,
        .offset = 0.0f,
        .min_value = -156.9f,
        .max_value = 156.9f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "lin_accel_y",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0047889f,
        .offset = 0.0f,
        .min_value = -156.9f,
        .max_value = 156.9f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "lin_accel_z",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0047889f,
        .offset = 0.0f,
        .min_value = -156.9f,
        .max_value = 156.9f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t gravity_accelerometer_signals[3] = {
    {
        .name = "gravity_x",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0002994f,
        .offset = 0.0f,
        .min_value = -9.81f,
        .max_value = 9.81f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "gravity_y",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0002994f,
        .offset = 0.0f,
        .min_value = -9.81f,
        .max_value = 9.81f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "gravity_z",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0002994f,
        .offset = 0.0f,
        .min_value = -9.81f,
        .max_value = 9.81f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t datetime_response_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t gnss_utc_response_signals[6] = {
    {
        .name = "utc_year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "utc_month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "utc_date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "utc_hours",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "utc_minutes",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "utc_seconds",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t rgb_led_set_signals[3] = {
    {
        .name = "red",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "green",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "blue",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t version_response_signals[4] = {
    {
        .name = "version_major",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_minor",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_patch",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_identifier",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

/** Public variables. *********************************************************/

const can_message_t momentum_dbc_messages[] = {
    {
        .name = "state",
        .message_id = 32,
        .id_mask = 0xFFFFFFFF,
        .dlc = 2,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = state_signals,
        .signal_count = 2,
    },
    {
        .name = "barometric",
        .message_id = 64,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = barometric_signals,
        .signal_count = 3,
    },
    {
        .name = "gnss1",
        .message_id = 96,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = gnss1_signals,
        .signal_count = 2,
    },
    {
        .name = "gnss2",
        .message_id = 128,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = gnss2_signals,
        .signal_count = 5,
    },
    {
        .name = "gnss3",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = gnss3_signals,
        .signal_count = 3,
    },
    {
        .name = "quaternion",
        .message_id = 192,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = quaternion_signals,
        .signal_count = 4,
    },
    {
        .name = "gyroscope",
        .message_id = 224,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = gyroscope_signals,
        .signal_count = 3,
    },
    {
        .name = "magnetometer",
        .message_id = 256,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = magnetometer_signals,
        .signal_count = 3,
    },
    {
        .name = "accelerometer",
        .message_id = 288,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = accelerometer_signals,
        .signal_count = 3,
    },
    {
        .name = "linear_accelerometer",
        .message_id = 320,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = linear_accelerometer_signals,
        .signal_count = 3,
    },
    {
        .name = "gravity_accelerometer",
        .message_id = 352,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = gravity_accelerometer_signals,
        .signal_count = 3,
    },
    {
        .name = "datetime_get",
        .message_id = 384,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "datetime_response",
        .message_id = 416,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_response_signals,
        .signal_count = 7,
    },
    {
        .name = "gnss_utc_get",
        .message_id = 448,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "gnss_utc_response",
        .message_id = 480,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = gnss_utc_response_signals,
        .signal_count = 6,
    },
    {
        .name = "rgb_led_set",
        .message_id = 512,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = rgb_led_set_signals,
        .signal_count = 3,
    },
    {
        .name = "version_get",
        .message_id = 960,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "version_response",
        .message_id = 992,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = version_response_signals,
        .signal_count = 4,
    },
};
