/*******************************************************************************
 * VENDORED FILE - DO NOT EDIT.
 * Source: https://github.com/scalpelspace/mc_brushed_driver
 * Version: 0d4eb85 (ref: HEAD)
 * Synced by CI tooling.
 *******************************************************************************
 */

/*******************************************************************************
 * @file mc_brushed_can_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "mc_brushed_can_dbc.h"

/** Private variables. ********************************************************/

static const can_signal_t state_signals[4] = {
    {
        .name = "system_state",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "fault",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "drv8873s_fault_reg",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "drv8873s_diag_reg",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t command_brushed_signals[9] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "control_mode",
        .start_bit = 8,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_SELECTOR,
        .mux_value = 0,
    },
    {
        .name = "enable",
        .start_bit = 11,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "clear_faults",
        .start_bit = 12,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "reserved0",
        .start_bit = 13,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "target_torque",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0001f,
        .offset = 0.0f,
        .min_value = -214748.3648f,
        .max_value = 214748.3647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "target_velocity",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "target_position_rel",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 3,
    },
    {
        .name = "target_hbridge_ol",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0001f,
        .offset = 0.0f,
        .min_value = -1.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 4,
    },
};

static const can_signal_t command_brushed_zero_signals[1] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t sensor_signals[3] = {
    {
        .name = "drv8873s_ipropi",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 4095.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "encoder_raw_count",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = -32768.0f,
        .max_value = 32767.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "encoder_position",
        .start_bit = 32,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_diagnostic_signals[4] = {
    {
        .name = "torque_error",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -32.768f,
        .max_value = 32.767f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "velocity_error",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -32.768f,
        .max_value = 32.767f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "position_error",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0001f,
        .offset = 0.0f,
        .min_value = -3.2768f,
        .max_value = 3.2767f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "duty_command",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0001f,
        .offset = 0.0f,
        .min_value = -1.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_config_set_signals[12] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "controller",
        .start_bit = 8,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_SELECTOR,
        .mux_value = 0,
    },
    {
        .name = "reserved0",
        .start_bit = 11,
        .bit_length = 5,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "torque_k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 0,
    },
    {
        .name = "velocity_k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "position_k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "torque_k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 0,
    },
    {
        .name = "velocity_k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "position_k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "torque_k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 0,
    },
    {
        .name = "velocity_k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "position_k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
};

static const can_signal_t controls_config_get_signals[3] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "controller",
        .start_bit = 8,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_SELECTOR,
        .mux_value = 0,
    },
    {
        .name = "reserved0",
        .start_bit = 11,
        .bit_length = 5,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_config_response_signals[12] = {
    {
        .name = "reserved0",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "controller",
        .start_bit = 8,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_SELECTOR,
        .mux_value = 0,
    },
    {
        .name = "reserved1",
        .start_bit = 11,
        .bit_length = 5,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "torque_k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 0,
    },
    {
        .name = "velocity_k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "position_k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "torque_k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 0,
    },
    {
        .name = "velocity_k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "position_k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "torque_k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 0,
    },
    {
        .name = "velocity_k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "position_k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
};

static const can_signal_t datetime_set_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t datetime_get_response_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t rgb_led_set_signals[3] = {
    {
        .name = "red",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "green",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "blue",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t version_get_response_signals[4] = {
    {
        .name = "version_major",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_minor",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_patch",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_identifier",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

/** Public variables. *********************************************************/

const can_message_t mc_brushed_dbc_messages[] = {
    {
        .name = "state",
        .message_id = 32,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = state_signals,
        .signal_count = 4,
    },
    {
        .name = "command_brushed",
        .message_id = 64,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = command_brushed_signals,
        .signal_count = 9,
    },
    {
        .name = "command_brushed_zero",
        .message_id = 96,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = command_brushed_zero_signals,
        .signal_count = 1,
    },
    {
        .name = "sensor",
        .message_id = 128,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = sensor_signals,
        .signal_count = 3,
    },
    {
        .name = "controls_diagnostic",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_diagnostic_signals,
        .signal_count = 4,
    },
    {
        .name = "controls_config_set",
        .message_id = 192,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_config_set_signals,
        .signal_count = 12,
    },
    {
        .name = "controls_config_get",
        .message_id = 224,
        .id_mask = 0xFFFFFFFF,
        .dlc = 2,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_config_get_signals,
        .signal_count = 3,
    },
    {
        .name = "controls_config_response",
        .message_id = 256,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_config_response_signals,
        .signal_count = 12,
    },
    {
        .name = "datetime_set",
        .message_id = 288,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_set_signals,
        .signal_count = 7,
    },
    {
        .name = "datetime_get",
        .message_id = 320,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "datetime_get_response",
        .message_id = 352,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_get_response_signals,
        .signal_count = 7,
    },
    {
        .name = "rgb_led_set",
        .message_id = 384,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = rgb_led_set_signals,
        .signal_count = 3,
    },
    {
        .name = "version_get",
        .message_id = 960,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "version_get_response",
        .message_id = 992,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = version_get_response_signals,
        .signal_count = 4,
    },
};
