/*******************************************************************************
 * VENDORED FILE - DO NOT EDIT.
 * Source: https://github.com/scalpelspace/mc_stepper_driver
 * Version: 7b3c9dd (ref: v0.2.1)
 * Synced by CI tooling.
 *******************************************************************************
 */

/*******************************************************************************
 * @file mc_stepper_can_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "mc_stepper_can_dbc.h"

/** Private variables. ********************************************************/

static const can_signal_t state_signals[4] = {
    {
        .name = "system_state",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "mcu_temperature",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = -40.0f,
        .min_value = -40.0f,
        .max_value = 215.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "fault",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "tmc2209_status",
        .start_bit = 24,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t stallguard_event_signals[4] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "sg_result",
        .start_bit = 8,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1023.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "sgthrs",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "stalled",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t command_stepper_signals[9] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "control_mode",
        .start_bit = 8,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_SELECTOR,
        .mux_value = 0,
    },
    {
        .name = "enable",
        .start_bit = 11,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "clear_faults",
        .start_bit = 12,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "reserved0",
        .start_bit = 13,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "target_position_abs",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "target_velocity",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "target_position_rel",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 3,
    },
    {
        .name = "target_position_ol",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 4,
    },
};

static const can_signal_t command_stepper_zero_signals[1] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t sensor_signals[2] = {
    {
        .name = "encoder_raw_count",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = -32768.0f,
        .max_value = 32767.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "encoder_position",
        .start_bit = 16,
        .bit_length = 32,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -2147483.648f,
        .max_value = 2147483.647f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_diagnostic_signals[4] = {
    {
        .name = "position_setpoint",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -32.768f,
        .max_value = 32.767f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "position_error",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.0001f,
        .offset = 0.0f,
        .min_value = -3.2768f,
        .max_value = 3.2767f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "velocity_setpoint",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = -32.768f,
        .max_value = 32.767f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "step_rate_command",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = true,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = -32768.0f,
        .max_value = 32767.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t motion_config_set_signals[4] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "step_size",
        .start_bit = 8,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 256.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "max_acceleration",
        .start_bit = 24,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.1f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 6553.5f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "max_velocity",
        .start_bit = 40,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t motion_config_get_signals[1] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t motion_config_response_signals[3] = {
    {
        .name = "step_size",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 256.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "max_acceleration",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.1f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 6553.5f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "max_velocity",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t current_config_set_signals[5] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "run_current_ma",
        .start_bit = 8,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 3000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_run",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_hold",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_hold_delay",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 15.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t current_config_get_signals[1] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t current_config_response_signals[4] = {
    {
        .name = "run_current_ma",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 3000.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_run",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_hold",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_hold_delay",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 15.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_config_set_signals[5] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "reserved0",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "k_p",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "k_i",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "k_d",
        .start_bit = 48,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_config_get_signals[1] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t controls_config_response_signals[3] = {
    {
        .name = "k_p",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "k_i",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "k_d",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 0.001f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65.535f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t stallguard_set_signals[3] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "enable",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "sgthrs",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t stallguard_get_signals[1] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t stallguard_response_signals[4] = {
    {
        .name = "enable",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "sgthrs",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "sg_result",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1023.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "stalled",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t datetime_set_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t datetime_response_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t rgb_led_set_signals[3] = {
    {
        .name = "red",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "green",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "blue",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t version_response_signals[4] = {
    {
        .name = "version_major",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_minor",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_patch",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_identifier",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

/** Public variables. *********************************************************/

const can_message_t mc_stepper_dbc_messages[] = {
    {
        .name = "state",
        .message_id = 32,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = state_signals,
        .signal_count = 4,
    },
    {
        .name = "stallguard_event",
        .message_id = 64,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = stallguard_event_signals,
        .signal_count = 4,
    },
    {
        .name = "command_stepper",
        .message_id = 96,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = command_stepper_signals,
        .signal_count = 9,
    },
    {
        .name = "command_stepper_zero",
        .message_id = 128,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = command_stepper_zero_signals,
        .signal_count = 1,
    },
    {
        .name = "sensor",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = sensor_signals,
        .signal_count = 2,
    },
    {
        .name = "controls_diagnostic",
        .message_id = 192,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_diagnostic_signals,
        .signal_count = 4,
    },
    {
        .name = "motion_config_set",
        .message_id = 224,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = motion_config_set_signals,
        .signal_count = 4,
    },
    {
        .name = "motion_config_get",
        .message_id = 256,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = motion_config_get_signals,
        .signal_count = 1,
    },
    {
        .name = "motion_config_response",
        .message_id = 288,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = motion_config_response_signals,
        .signal_count = 3,
    },
    {
        .name = "current_config_set",
        .message_id = 320,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_config_set_signals,
        .signal_count = 5,
    },
    {
        .name = "current_config_get",
        .message_id = 352,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_config_get_signals,
        .signal_count = 1,
    },
    {
        .name = "current_config_response",
        .message_id = 384,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_config_response_signals,
        .signal_count = 4,
    },
    {
        .name = "controls_config_set",
        .message_id = 416,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_config_set_signals,
        .signal_count = 5,
    },
    {
        .name = "controls_config_get",
        .message_id = 448,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_config_get_signals,
        .signal_count = 1,
    },
    {
        .name = "controls_config_response",
        .message_id = 480,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = controls_config_response_signals,
        .signal_count = 3,
    },
    {
        .name = "stallguard_set",
        .message_id = 512,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = stallguard_set_signals,
        .signal_count = 3,
    },
    {
        .name = "stallguard_get",
        .message_id = 544,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = stallguard_get_signals,
        .signal_count = 1,
    },
    {
        .name = "stallguard_response",
        .message_id = 576,
        .id_mask = 0xFFFFFFFF,
        .dlc = 5,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = stallguard_response_signals,
        .signal_count = 4,
    },
    {
        .name = "datetime_set",
        .message_id = 608,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_set_signals,
        .signal_count = 7,
    },
    {
        .name = "datetime_get",
        .message_id = 640,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "datetime_response",
        .message_id = 672,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_response_signals,
        .signal_count = 7,
    },
    {
        .name = "rgb_led_set",
        .message_id = 704,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = rgb_led_set_signals,
        .signal_count = 3,
    },
    {
        .name = "version_get",
        .message_id = 960,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "version_response",
        .message_id = 992,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = version_response_signals,
        .signal_count = 4,
    },
};
