/*******************************************************************************
 * VENDORED FILE - DO NOT EDIT.
 * Source: https://github.com/scalpelspace/can_driver
 * Version: 972bdec (ref: v0.5.0)
 * Synced by CI tooling.
 *******************************************************************************
 */

/*******************************************************************************
 * @file can_id_allocation_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "can_id_allocation_dbc.h"

/** Private variables. ********************************************************/

static const can_signal_t node_id_discover_signals[1] = {
    {
        .name = "session_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t node_id_advertise_signals[5] = {
    {
        .name = "uid_hash48_0",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "uid_hash48_1",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "uid_hash48_2",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "session_id",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "RESERVED_ADVERTISE",
        .start_bit = 56,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t node_id_assign_signals[6] = {
    {
        .name = "uid_hash48_0",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "uid_hash48_1",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "uid_hash48_2",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "session_id",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "node_id",
        .start_bit = 56,
        .bit_length = 5,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "RESERVED_ASSIGN",
        .start_bit = 61,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t node_id_ack_00_signals[6] = {
    {
        .name = "uid_hash48_0",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "uid_hash48_1",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "uid_hash48_2",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "session_id",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "node_id",
        .start_bit = 56,
        .bit_length = 5,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "RESERVED_ACKNOWLEDGE",
        .start_bit = 61,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

/** Public variables. *********************************************************/

const can_message_t allocation_dbc[] = {
    {
        .name = "node_id_discover",
        .message_id = 1823,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = node_id_discover_signals,
        .signal_count = 1,
    },
    {
        .name = "node_id_advertise",
        .message_id = 1824,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = node_id_advertise_signals,
        .signal_count = 5,
    },
    {
        .name = "node_id_assign",
        .message_id = 1887,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = node_id_assign_signals,
        .signal_count = 6,
    },
    {
        .name = "node_id_ack_00",
        .message_id = 1888,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = node_id_ack_00_signals,
        .signal_count = 6,
    },
};
